# Generated by Django 2.2.24 on 2023-06-14 17:29
import phonenumbers

from django.db import migrations


def fill_pure_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phonenumber):
            formatted_phonenumber = phonenumbers.format_number(
                phonenumber, phonenumbers.PhoneNumberFormat.E164
            )
            flat.owner_pure_phone = formatted_phonenumber
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [migrations.RunPython(fill_pure_number)]
