# Generated by Django 2.2.24 on 2023-06-15 06:57

from django.db import migrations


def migrate_owner_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            defaults={'owner_pure_phone': flat.owner_pure_phone},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230615_0946'),
    ]

    operations = [migrations.RunPython(migrate_owner_data)]
