# Generated by Django 2.2.24 on 2023-06-15 11:57

from django.db import migrations


def fill_ownership_relations(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        owner, status = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            defaults={'owner_pure_phone': flat.owner_pure_phone},
        )
        if not flat in owner.own_property.all():
            owner.own_property.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230615_1457'),
    ]

    operations = [migrations.RunPython(fill_ownership_relations)]
